spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Guarda los datos en una carpeta física local llamada "datos"
spring.datasource.url=jdbc:h2:file:./datos/langileakdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update